---

prefixes:
    - "libreswan_config_"

classes:
  - libreswan_config

dependencies:
  - libreswan_config
  - libreswan
  - stdlib
  - concat

libreswan_config::purge_configdir: "%{::libreswan_config_purge_configdir}"
libreswan_config::ipsec_config:
  listen: "%{::libreswan_config_listen}"
  dumpdir: "%{::libreswan_config_dumpdir}"
  virtual_private: "%{::libreswan_config_virtual_private}"
  protostack: "%{::libreswan_config_protostack}"
  plutostderrlog: "%{::libreswan_config_plutostderrlog}"
  keep_alive: "%{::libreswan_config_keep_alive}"
