---

prefixes: 
  - "logstash_config_config_file_"

classes:
  - logstash_config

dependencies:
  - logstash_config
  - logstash
  - stdlib
  - file_concat

logstash_config::config_files:
    "%{::logstash_config_config_file_name}":
        source: "%{::logstash_config_config_file_source}"
