---

prefixes: 
    - "noconfigpkgs_"

classes:
  - noconfigpkgs

dependencies:
  - noconfigpkgs
  - stdlib

#install gems
noconfigpkgs::default_gems:
  RedHat :
    - "%{::noconfigpkgs_redhat_gem}"

